name: kumbh-milap

services:

  # server:
  #   container_name: server
  #   build: ./server
  #   ports:
  #     - "3001:3001/tcp"
  #   volumes:
  #     - "./server:/home/app/server"
  #   restart: unless-stopped
  #   env_file:
  #     - "./server/.env"

  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: kumbh
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./server/db/my.cnf:/etc/mysql/my.cnf
volumes:
  mysql_data: