name: kumbh_milap
description: "Application to help people find like minded ones in the Kumbh Mela"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  geolocator: ^13.0.2
  intl: any
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1
  http: ^1.3.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.1
  either_dart: ^1.0.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
